sudo: required

language: cpp

os:
  - linux
  - osx

branches:
  except:
    - /^v[0-9]/

git:
  depth: 999999

env:
  global:
    - MYPYTHON_VERSION=2.7
  matrix:
    - MYUSEMC=true
    - MYUSEMC=false

matrix:
  exclude:
    - os: osx
      env: MYUSEMC=false


before_install:
  - umask 022
  - git fetch origin --tags
  - if ${MYUSEMC}; then
        NOAPT=true; NOMC=false;
    else
        NOAPT=false; NOMC=true;
        MYPIPFLAGS="--user";
    fi
  - MYMCREPO=https://repo.continuum.io/miniconda
  - case ${TRAVIS_OS_NAME} in
    linux)
        MYMCBUNDLE=Miniconda-latest-Linux-x86_64.sh ;;
    osx)
        MYMCBUNDLE=Miniconda-latest-MacOSX-x86_64.sh ;;
    *)
        echo "Unsupported operating system." >&2;
        exit 2 ;;
    esac

  - mkdir -p ~/pkgs/

  - $NOMC || pushd ~/pkgs/
  - $NOMC || wget --timestamping ${MYMCREPO}/${MYMCBUNDLE}
  - $NOMC || test -x ~/mc/bin/conda || bash ${MYMCBUNDLE} -b -f -p ~/mc
  - $NOMC || popd
  - $NOMC || export PATH="${HOME}/mc/bin:${PATH}"
  - $NOMC || conda update --yes conda
  - $NOMC || conda install --yes python=${MYPYTHON_VERSION} conda-build
  - $NOMC || conda create --name=testenv --yes python=${MYPYTHON_VERSION}
  - $NOMC || conda config --add channels pavoljuhas/channel/dev
  - $NOMC || conda config --add channels pavoljuhas

  - $NOAPT || test "${TRAVIS_OS_NAME}" = "linux"
  - $NOAPT || sudo apt-get update -qq
  - $NOAPT || sudo apt-get install -y
                  libboost-all-dev python-pip build-essential scons
  - $NOAPT || scons sdist
  - $NOAPT || MYTARBUNDLE="$(ls -t "${PWD}"/*.tar.gz | head -1)"
  - $NOAPT || tar xzf "${MYTARBUNDLE}" -C ~/pkgs/


install:
  - $NOMC || conda build conda-recipe
  - $NOMC || conda list --name=_test --export libobjcryst > /tmp/mypackage.txt
  - $NOMC || source activate testenv
  - $NOMC || conda install --yes --use-local --file=/tmp/mypackage.txt
  - $NOMC || conda install --yes scons
  - $NOMC || MYPREFIX="${HOME}/mc/envs/testenv"
  - $NOMC || MYWORKDIR="${HOME}/mc/conda-bld/work"

  - $NOAPT || cd ~/pkgs/"$(basename "${MYTARBUNDLE}" .tar.gz)"/
  - $NOAPT || scons build=fast
  - $NOAPT || sudo scons build=fast install
  - $NOAPT || MYPREFIX=/usr/local
  - $NOAPT || MYWORKDIR=$PWD

  # Ensure libObjCryst cannot be loaded from the work directory.
  - scons build=fast -Q -C "${MYWORKDIR}" --clean lib
  - MYINCLUDE="${MYPREFIX}/include"
  - MYLIB="${MYPREFIX}/lib"
  - MYVERSION="${MYINCLUDE}/ObjCryst/version.h"
  - MYGIT_REV=$(grep '^#define LIBOBJCRYST_GIT_SHA' "$MYVERSION" | cut -d '"' -f 2)
  - if [[ "${TRAVIS_COMMIT}" != "${MYGIT_REV}" ]]; then
        echo "Version mismatch ${TRAVIS_COMMIT} vs ${MYGIT_REV}.";
        exit 1;
    fi

  - $NOMC || export LIBRARY_PATH="${MYLIB}"
  - $NOMC || export CPATH="${MYINCLUDE}"
  - $NOMC || MYLINKFLAGS="-Wl,-rpath,${MYLIB}"

    # Mac OS X must use the same deployment target as conda-build.
  - if $MYUSEMC && [[ "${TRAVIS_OS_NAME}" == osx ]]; then
        export MACOSX_DEPLOYMENT_TARGET=10.6;
    fi


before_script:
  - cd "${MYWORKDIR}/examples"


script:
  - $CXX -o testlib testlib.cpp -lObjCryst $MYLINKFLAGS
  - ./testlib


#after_success:
# - pip install $MYPIPFLAGS codecov
# - codecov
