{% set setupdata = load_setup_py_data(from_recipe_dir=True) %}

package:
  name: libobjcryst
  version: {{ setupdata['version'] }}

source:
  # git_url: https://github.com/diffpy/libobjcryst.git
  git_url: ..

build:
  number: 0

requirements:
  build:
    - scons
    - boost-all 1.59.0

test:
  commands:
    # Dummy test, but it ensures there is _test environment needed by travis.
    - true

about:
  home: https://github.com/diffpy/libobjcryst/
  summary: ObjCryst++ packaged for installation as a shared library.
  license: GPLv2
  license_file: LICENSE.txt
