package:
  name: libobjcryst
  ## Use __conda_version__.txt.
  # version: 2015.1

source:
  # git_url: https://github.com/diffpy/libobjcryst.git
  git_url: ..

build:
  number: 0
  binary_relocation: False      # [linux]

requirements:
  build:
    - scons
    - boost 1.57.0              # [linux]
    - boost 1.56.0 py27_2       # [osx]

test:
  commands:
    # Dummy test, but it ensures there is _test environment needed by travis.
    - true

about:
  home: https://github.com/diffpy/libobjcryst/
  license: GPLv2
  license_file: LICENSE.txt
