{% set setupdata = load_setup_py_data(from_recipe_dir=True) %}

package:
  name: libobjcryst
  version: {{ setupdata['version'] }}

source:
  # git_url: https://github.com/diffpy/libobjcryst.git
  git_url: ..
  # path: ..  # To build from modified local tree

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libobjcryst', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - scons
    - python
  host:
    - boost {{ boost }}


test:
  commands:
    - test -f $PREFIX/lib/libObjCryst${SHLIB_EXT}             # [not win]
    - test -f $PREFIX/include/ObjCryst/version.h              # [not win]
    - if not exist %LIBRARY_LIB%\\libObjCryst.lib exit 1      # [win]
    - if not exist %LIBRARY_INC%\\ObjCryst\\version.h exit 1  # [win]

about:
  home: https://github.com/diffpy/libobjcryst/
  summary: ObjCryst++ packaged for installation as a shared library.
  license: GPLv2
  license_file: LICENSE.txt
